language: julia
sudo: false
os:
    - linux

julia:
    - 1.0
    - nightly
        
allow_failures:
    - julia: nightly

notifications:
    email: false

script:
    - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("StreamGraphs"); Pkg.test("StreamGraphs"; coverage=true)'
        
after_success:
    - julia -e 'using Pkg; cd(Pkg.dir("StreamGraphs")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

jobs:
    include:
        - stage: "Documentation"
          julia: 1.0
          os: linux
          script:
            - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.build("StreamGraphs"); Pkg.instantiate()'
            - julia --project=docs/ docs/make.jl
          after_success: skip
